# Archive disposition action labels
action.archive.title=Archive to Filesystem
actions.archive=Archive to Filesystem
message.archive.success={0} successfully archived
message.archive.failure={0} archive failed
